In [1]:
import numpy as np

In [2]:
import pandas as pd

In [7]:
list1=[1,2,3,4]
list2=['a','b','c','d']
series1=pd.Series(data=list1,index=list2)
print(series1)

a    1
b    2
c    3
d    4
dtype: int64


In [8]:
s1=pd.Series([12,13,14,15],('a','s','d','f'))
s1

a    12
s    13
d    14
f    15
dtype: int64

In [9]:
s1[3]

15

In [11]:
s1+series1

a    13.0
b     NaN
c     NaN
d    18.0
f     NaN
s     NaN
dtype: float64

In [6]:
np.random.randn(3,4)

array([[ 0.47580723, -0.56829725,  0.29624066,  0.62634495],
       [-0.90822897, -1.59888115,  0.54199456, -0.56074104],
       [ 0.99394162,  0.74283963,  0.29163637,  2.48074096]])

In [14]:
np.random.seed(10)
np.random.randint(1,3,6).reshape(2,3)

array([[2, 2, 1],
       [2, 1, 2]])

In [21]:
df1=pd.DataFrame(np.arange(1,7).reshape(2,3),['A','B'],['W','X','Y'])
df1

W  X  Y
A  1  2  3
B  4  5  6

In [18]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
df2=pd.DataFrame(np.random.randint(1,6,15).reshape(5,3),['USA','INDIA','NEWZEALAND','ENGLAND','AUSTRALIA'],['A','B','C'])
df2

A  B  C
USA         1  2  2
INDIA       4  5  4
NEWZEALAND  3  5  5
ENGLAND     4  1  5
AUSTRALIA   1  4  2

df2['A']

In [28]:
df2['A']

USA           4
INDIA         5
NEWZEALAND    1
ENGLAND       1
AUSTRALIA     5
Name: A, dtype: int32

In [29]:
df2.loc['USA']

A    4
B    5
C    2
Name: USA, dtype: int32

In [30]:
type(df2)

pandas.core.frame.DataFrame

In [31]:
type(df2["A"])

pandas.core.series.Series

In [32]:
df2[['A','B']]

A  B
USA         4  5
INDIA       5  3
NEWZEALAND  1  5
ENGLAND     1  1
AUSTRALIA   5  3

In [34]:
df2.loc[['USA','INDIA'],["A",'B']]

A  B
USA    4  5
INDIA  5  3

In [4]:
df2['sum']=df2['A']+df2['B']+df2['C']
df2

A  B  C  sum
USA         1  2  2    5
INDIA       4  5  4   13
NEWZEALAND  3  5  5   13
ENGLAND     4  1  5   10
AUSTRALIA   1  4  2    7

In [5]:
df2.drop('sum',axis=1,inplace=True)

In [6]:
df2

A  B  C
USA         1  2  2
INDIA       4  5  4
NEWZEALAND  3  5  5
ENGLAND     4  1  5
AUSTRALIA   1  4  2

In [7]:
df2[df2>1]

A    B  C
USA         NaN  2.0  2
INDIA       4.0  5.0  4
NEWZEALAND  3.0  5.0  5
ENGLAND     4.0  NaN  5
AUSTRALIA   NaN  4.0  2

In [36]:
df2[df2>2][['A','B']]

A    B
USA         NaN  NaN
INDIA       5.0  NaN
NEWZEALAND  NaN  5.0
ENGLAND     NaN  NaN
AUSTRALIA   5.0  4.0

In [40]:
df2[df2['A']>2][['A','B']]

A  B
INDIA      5  2
AUSTRALIA  5  4

In [42]:
df2[(df2['A']>2)&(df2['B']>2)][['A','B']]

A  B
AUSTRALIA  5  4

In [43]:
df2.reset_index()

index  A  B  C  SUM
0         USA  2  2  4    8
1       INDIA  5  2  3   10
2  NEWZEALAND  1  5  4   10
3     ENGLAND  2  1  2    5
4   AUSTRALIA  5  4  4   13

In [22]:
list1=['X','Y','Z','U','V']
df2['Index']=list1
df2

A  B  C Index
USA         1  2  2     X
INDIA       4  5  4     Y
NEWZEALAND  3  5  5     Z
ENGLAND     4  1  5     U
AUSTRALIA   1  4  2     V

In [23]:
df2.set_index('Index')

A  B  C
Index         
X      1  2  2
Y      4  5  4
Z      3  5  5
U      4  1  5
V      1  4  2

In [26]:
dic_1={'A':[1,2,np.nan],'B':[4,np.nan,np.nan],'C':[6,7,8]}
dic_1

{'A': [1, 2, nan], 'B': [4, nan, nan], 'C': [6, 7, 8]}

In [28]:
df_1=pd.DataFrame(dic_1)
df_1

A    B  C
0  1.0  4.0  6
1  2.0  NaN  7
2  NaN  NaN  8

In [29]:
df_1.dropna()

A    B  C
0  1.0  4.0  6

In [30]:
df_1.dropna(axis=1,thresh=2)

A  C
0  1.0  6
1  2.0  7
2  NaN  8

In [32]:
#df_1.fillna(value=2)

In [33]:
df_1

A    B  C
0  1.0  4.0  6
1  2.0  NaN  7
2  NaN  NaN  8

In [37]:
df_1.fillna(value=df_1['A'].mean())

A    B  C
0  1.0  4.0  6
1  2.0  1.5  7
2  1.5  1.5  8

In [4]:
df_data=pd.DataFrame({'Country':['Usa','India','England','Bangladesh','India','Usa'],'Company':['FB','GG','BR','AMA','FB','GG'],'Sales':[120,240,450,100,200,300]})
df_data

Country Company  Sales
0         Usa      FB    120
1       India      GG    240
2     England      BR    450
3  Bangladesh     AMA    100
4       India      FB    200
5         Usa      GG    300

In [6]:
df_data.groupby('Country').mean()

Sales
Country          
Bangladesh    100
England       450
India         220
Usa           210

In [9]:
df_data.groupby('Company').sum().loc['GG']

Sales    540
Name: GG, dtype: int64

In [13]:
df_data['Sales'].apply(lambda a:a*2)

0    240
1    480
2    900
3    200
4    400
5    600
Name: Sales, dtype: int64

In [9]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [4]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [7]:
dF=pd.DataFrame(np.random.randint(0,100,30).reshape(6,5),index=hier_index,columns='A B C D E'.split())
dF

A   B   C   D   E
G1 1  55  30  35  94  52
   2  93  18  56  33  11
   3  16  33  65  30  46
G2 1   3  69  55  51  29
   2  92   0  32   3  96
   3   8   6  36  75  88

In [10]:
dF.index.names=['Group','Num']
dF

A   B   C   D   E
Group Num                    
G1    1    55  30  35  94  52
      2    93  18  56  33  11
      3    16  33  65  30  46
G2    1     3  69  55  51  29
      2    92   0  32   3  96
      3     8   6  36  75  88

In [11]:
dF.xs(1,level='Num')

A   B   C   D   E
Group                    
G1     55  30  35  94  52
G2      3  69  55  51  29

In [18]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K4'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})   

In [19]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [20]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K4  C3  D3

In [21]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2

In [22]:
pd.merge(left,right,how='outer',on='key')

key    A    B    C    D
0  K0   A0   B0   C0   D0
1  K1   A1   B1   C1   D1
2  K2   A2   B2   C2   D2
3  K3   A3   B3  NaN  NaN
4  K4  NaN  NaN   C3   D3

In [23]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [24]:
left

key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [25]:
right

key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [27]:
pd.merge(left,right,on=['key1','key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [28]:
pd.merge(left,right,how='outer',on=['key1','key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [5]:
inf1=pd.read_csv('info_pan.csv')
inf1

Name  Subject  Marks
0    Sam    Maths     99
1   uday  science     54
2  Fahad   social     36